eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      deafultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
microservice:
  order-service:
    endpoints:
      order:
        uri: http://ORDER-SERVICE/orders/bookOrder    
  payment-service:
    endpoints:
      payment:
        uri: http://PAYMENT-SERVICE/payments/doPayment
